[package]
name = "playage"
version = "0.1.0"
authors = ["Ren√©e Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
aoc-userpatch = { path = "crates/aoc-userpatch" }
dprun = { path = "crates/dprun" }
dpsp-local-only = { path = "crates/dpsp-local-only" }
dpsp-libp2p = { path = "crates/dpsp-libp2p" }
rand = "^0.6.5"
tokio = "^0.1.20"

[workspace]
members = [
  "crates/aoc-userpatch",
  "crates/aoc-spectate",
  "crates/dprun",
  "crates/dpsp-libp2p",
  "crates/dpsp-local-only",
  "crates/wololokingdoms"
]
