[package]
name = "wololokingdoms"
version = "0.1.0"
authors = ["Ren√©e Kooi <renee@kooi.me>"]
edition = "2018"
build = "build.rs"

[dependencies]
# aoc_userpatch = { path = "../aoc_userpatch" }

[build-dependencies]
bindgen = "^0.51.0"
cmake = "^0.1.35"
