[package]
name = "dpsp-local-only"
version = "0.1.0"
authors = ["Ren√©e Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
async-std = "1.6.4"
async-trait = "0.1.41"
dprun = { path = "../dprun" }
futures = "0.3.6"
log = "0.4.11"
