[package]
name = "dpsp-local-only"
version = "0.1.0"
authors = ["Ren√©e Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
async-std = "1.9.0"
async-trait = "0.1.42"
dprun = { path = "../dprun" }
futures = "0.3.12"
log = "0.4.13"
