[package]
name = "dprun2"
version = "0.1.0"
authors = ["RenÃ©e Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
lazy_static = "1.4"
uuid = { version = "0.8", default-features = false }
async-std = { version = "1.4", default-features = false, features = ["unstable"] }
